---
language: python
python: "2.7"
matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
sudo: required

addons:
  apt:
    packages:
    - python-pip

install:
  # TODO this becomes unnecessary on trusty/indigo EOL
  # workaround from https://github.com/travis-ci/travis-ci/issues/9361
  # to upgrade to dpkg >= 1.17.5ubuntu5.8, which fixes https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627
  - sudo apt-get install -y dpkg
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local
  - source $(find /opt/ros -mindepth 2 -maxdepth 2 -name setup.bash)
  - which roscore

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
